import { resolveProposedExercise } from "../exerciseResolution.js";
import { PROGRAM_PROPOSAL_TYPES, PROGRAM_PROPOSAL_VERSION, validateProgramProposal } from "../programProposal.js";

const clone = (value) => structuredClone(value);
const text = (value) => typeof value === "string" ? value.trim() : "";
const validExercise = (value) => value && typeof value === "object" && /^wger-[A-Za-z0-9._:-]+$/.test(value.id) && text(value.name);
const sourceFor = (value) => value?.candidate?.candidate ?? value?.candidate ?? value;
const makeId = (prefix, factory) => typeof factory === "function" ? factory(prefix) : prefix + "-" + crypto.randomUUID();
const error = (code, message) => ({ code, message });
const dedupe = (items) => { const seen = new Set(); return (Array.isArray(items) ? items : []).filter(validExercise).filter((item) => !seen.has(item.id) && seen.add(item.id)).map(clone); };

export const ROB_PROGRAM_RESOLUTION_VERSION = 1;
export function createRobProgramResolutionFingerprint({ candidate, requirements }) { return JSON.stringify({ candidate: sourceFor(candidate), requirements: requirements ?? null }); }
export function createRobProgramResolutionSession({ candidate, requirements }) {
  const source = sourceFor(candidate); const program = source?.program;
  if (!source || source.proposalType !== "create_program" || !Array.isArray(program?.days)) return null;
  const entries = {};
  program.days.forEach((day, routineIndex) => (day.exercises ?? []).forEach((exercise, exerciseIndex) => { const key = "days." + routineIndex + ".exercises." + exerciseIndex; entries[key] = { key, routineIndex, exerciseIndex, requestedName: text(exercise.exerciseRef), status: "unresolved", candidates: [], selectedExercise: null, error: null }; }));
  return { version: ROB_PROGRAM_RESOLUTION_VERSION, candidate: clone(source), requirements: clone(requirements ?? null), fingerprint: createRobProgramResolutionFingerprint({ candidate: source, requirements }), entries, status: "not_started", proposal: null, validation: null };
}
const current = (session) => session?.version === ROB_PROGRAM_RESOLUTION_VERSION && session.fingerprint === createRobProgramResolutionFingerprint({ candidate: session.candidate, requirements: session.requirements });
const getEntry = (session, key) => current(session) && typeof key === "string" ? session.entries?.[key] ?? null : null;
const progress = (session) => { const entries = Object.values(session?.entries ?? {}); const matched = entries.filter((entry) => validExercise(entry.selectedExercise)).length; return { total: entries.length, matched, remaining: entries.length - matched, ambiguous: entries.filter((entry) => entry.status === "ambiguous").length, unresolved: entries.filter((entry) => entry.status === "unresolved" || entry.status === "error").length }; };
export const getRobProgramResolutionProgress = progress;
export function refreshRobProgramResolutionStatus(session) { if (!current(session)) return { ...session, status: "stale", proposal: null }; const state = progress(session); return { ...session, status: state.total && state.remaining === 0 ? "complete" : state.matched ? "needs_input" : "not_started" }; }
function update(session, key, patch) { const entry = getEntry(session, key); if (!entry) return { session, error: error("invalid_resolution_key", "This exercise no longer belongs to the generated program.") }; const entries = clone(session.entries); entries[key] = { ...entries[key], ...patch, selectedExercise: patch.selectedExercise === undefined ? entries[key].selectedExercise : patch.selectedExercise ? clone(patch.selectedExercise) : null }; return { session: { ...session, entries, proposal: null, validation: null }, error: null }; }
export async function resolveRobProgramExercises(session, { searchExercises, concurrency = 4 } = {}) {
  if (!current(session) || typeof searchExercises !== "function") return { session, error: error("stale_or_invalid_session", "Exercise matching needs to restart from the current generated program.") };
  const next = clone(session); const keys = Object.keys(next.entries); const cache = new Map(); const limit = Math.max(1, Math.min(8, concurrency));
  const resolve = async (key) => { const entry = next.entries[key]; if (entry.selectedExercise) return; try { if (!cache.has(entry.requestedName)) cache.set(entry.requestedName, resolveProposedExercise({ requestedName: entry.requestedName, exerciseProvider: searchExercises })); const result = await cache.get(entry.requestedName); const candidates = dedupe(result?.candidates); next.entries[key] = result?.status === "resolved" && validExercise(result.exercise) ? { ...entry, status: "resolved", candidates: dedupe([result.exercise]), selectedExercise: clone(result.exercise), error: null } : result?.status === "ambiguous" ? { ...entry, status: "ambiguous", candidates, selectedExercise: null, error: null } : { ...entry, status: "unresolved", candidates, selectedExercise: null, error: null }; } catch { next.entries[key] = { ...entry, status: "error", candidates: [], selectedExercise: null, error: "Fitbot could not search the exercise library. Try again without generating another program." }; } };
  for (let index = 0; index < keys.length; index += limit) await Promise.all(keys.slice(index, index + limit).map(resolve));
  return { session: refreshRobProgramResolutionStatus(next), error: null };
}
export async function searchRobProgramExercises(session, { key, query, searchExercises } = {}) { const entry = getEntry(session, key); if (!entry || typeof searchExercises !== "function") return { session, error: error("invalid_resolution_search", "That exercise cannot be searched in this program.") }; try { const updated = update(session, key, { candidates: dedupe(await searchExercises(text(query) || entry.requestedName)), error: null }); return { session: refreshRobProgramResolutionStatus(updated.session), error: null }; } catch { const updated = update(session, key, { status: "error", error: "Fitbot could not search the exercise library. Try again." }); return { session: refreshRobProgramResolutionStatus(updated.session), error: null }; } }
export function selectRobProgramExercise(session, { key, exerciseId } = {}) { const entry = getEntry(session, key); if (!entry) return { session, error: error("invalid_resolution_key", "This exercise no longer belongs to the generated program.") }; const selected = entry.candidates?.find((item) => item.id === exerciseId); if (!selected || !validExercise(selected)) return { session, error: error("untrusted_exercise_selection", "Choose an exercise returned by Fitbot's library search.") }; const updated = update(session, key, { status: "selected", selectedExercise: selected, error: null }); return { session: refreshRobProgramResolutionStatus(updated.session), error: null }; }
export function clearRobProgramExerciseSelection(session, { key } = {}) { const entry = getEntry(session, key); if (!entry) return { session, error: error("invalid_resolution_key", "This exercise no longer belongs to the generated program.") }; const updated = update(session, key, { status: entry.candidates.length ? "ambiguous" : "unresolved", selectedExercise: null, error: null }); return { session: refreshRobProgramResolutionStatus(updated.session), error: null }; }
export function materializeRobProgramProposal(session, { programs = [], createId } = {}) { if (!current(session)) return { session: { ...session, status: "stale", proposal: null }, proposal: null, validation: { valid: false, errors: [error("stale_session", "This generated program changed. Restart matching.")] } }; if (progress(session).remaining) return { session, proposal: null, validation: { valid: false, errors: [error("incomplete_resolution", "Match every exercise before preparing this program.")] } }; if (session.proposal) return { session, proposal: session.proposal, validation: session.validation }; const source = session.candidate.program; const proposalId = makeId("proposal-rob", createId); const programId = makeId("program-rob", createId); const proposal = { id: proposalId, version: PROGRAM_PROPOSAL_VERSION, proposalType: PROGRAM_PROPOSAL_TYPES.CREATE, title: text(source.name), summary: text(source.summary), program: { id: programId, name: text(source.name), days: source.days.map((day, routineIndex) => ({ id: makeId("routine-rob", createId), name: text(day.name), exercises: day.exercises.map((exercise, exerciseIndex) => { const selected = session.entries["days." + routineIndex + ".exercises." + exerciseIndex].selectedExercise; return { routineExerciseId: makeId("ri-rob", createId), exerciseId: selected.id, sets: exercise.sets, repRange: exercise.repRange, restSeconds: exercise.restSeconds, ...(exercise.note ? { note: exercise.note } : {}), ...(exercise.proposalGroupKey ? { proposalGroupKey: exercise.proposalGroupKey } : {}) }; }) })) } }; const validation = validateProgramProposal(proposal, programs); const next = { ...session, status: validation.valid ? "complete" : "validation_failed", proposal: validation.valid ? validation.normalizedProposal : null, validation }; return { session: next, proposal: next.proposal, validation }; }
