import { AiError } from "../ai/aiErrors.js";
import { createRobWeeklyProgrammingPolicy, assessRobSessionWorkload } from "../../../src/services/rob/robWeeklyProgrammingPolicy.js";
import { ROB_SELECTION_INTENTS } from "../../../src/services/rob/robExercisePlanningTaxonomy.js";

export const ROB_WEEKLY_BLUEPRINT_VERSION = 1;
// Representative strict fixtures measure about 3,100 tokens for four days and
// 3,768 for five days using a conservative character estimate.
export const ROB_WEEKLY_BLUEPRINT_MAX_OUTPUT_TOKENS = 4000;
const MUSCLES = new Set(["chest", "back", "legs", "shoulders", "arms", "glutes", "core"]);
const PATTERNS = new Set(["horizontal_push", "vertical_push", "horizontal_pull", "vertical_pull", "knee_dominant", "hinge", "trunk", "conditioning", "isolation"]);
const ROLES = new Set(["compound", "isolation", "trunk", "conditioning"]);
const PRIORITIES = new Set(["primary", "standard", "accessory"]);
const INVOLVEMENT = new Set(["meaningful", "supporting", "unknown"]);
const SELECTION_INTENTS = new Set(ROB_SELECTION_INTENTS);
const object = (value) => value && typeof value === "object" && !Array.isArray(value);
const allowed = (value, keys) => object(value) && Object.keys(value).every((key) => keys.includes(key));
const text = (value, maximum) => typeof value === "string" && value.trim().length > 0 && value.trim().length <= maximum;
const list = (value, maximum, predicate) => Array.isArray(value) && value.length <= maximum && value.every(predicate);
const repRange = (value) => typeof value === "string" && /^(\d{1,3})(?:\s*-\s*(\d{1,3}))?$/.test(value) && (() => { const [, low, high = low] = value.match(/^(\d{1,3})(?:\s*-\s*(\d{1,3}))?$/); return Number(low) >= 1 && Number(high) <= 100 && Number(low) <= Number(high); })();
const fail = (reason, diagnostic = {}) => { const error = new AiError("ai_invalid_response", { retryable: true }); error.validationDiagnostic = { reason, ...diagnostic }; throw error; };
const invalid = (reason) => { const error = new AiError("ai_invalid_request"); error.validationDiagnostic = { reason }; throw error; };
const sameList = (first, second) => Array.isArray(first) && Array.isArray(second) && first.length === second.length && first.every((item, index) => item === second[index]);
const compatibleRole = (movementPattern, role) => ({ compound: ["horizontal_push", "vertical_push", "horizontal_pull", "vertical_pull", "knee_dominant", "hinge"], isolation: ["isolation"], trunk: ["trunk"], conditioning: ["conditioning"] }[role]?.includes(movementPattern));

const validRequirements = (requirements) => object(requirements) && requirements.version === 1 && typeof requirements.goal === "string" && Number.isInteger(requirements.daysPerWeek) && requirements.daysPerWeek >= 1 && requirements.daysPerWeek <= 6 && Number.isInteger(requirements.sessionMinutes) && requirements.sessionMinutes >= 20 && requirements.sessionMinutes <= 180 && Array.isArray(requirements.priorities) && Array.isArray(requirements.equipment) && typeof requirements.environment === "string" && typeof requirements.constraints === "string";
const slotValid = (slot) => allowed(slot, ["primaryMuscle", "secondaryStimulus", "movementPattern", "role", "selectionIntent", "sets", "repRange", "restSeconds", "priority", "sequencing", "fatigueConsideration", "flexibility"])
  && MUSCLES.has(slot.primaryMuscle) && list(slot.secondaryStimulus, 4, (item) => allowed(item, ["muscleGroup", "involvement"]) && MUSCLES.has(item.muscleGroup) && INVOLVEMENT.has(item.involvement))
  && PATTERNS.has(slot.movementPattern) && ROLES.has(slot.role) && compatibleRole(slot.movementPattern, slot.role) && (slot.selectionIntent === undefined || slot.selectionIntent === null || SELECTION_INTENTS.has(slot.selectionIntent)) && Number.isInteger(slot.sets) && slot.sets >= 1 && slot.sets <= 12 && repRange(slot.repRange) && Number.isInteger(slot.restSeconds) && slot.restSeconds >= 0 && slot.restSeconds <= 600 && PRIORITIES.has(slot.priority)
  && allowed(slot.sequencing, ["order", "rationale"]) && Number.isInteger(slot.sequencing.order) && slot.sequencing.order >= 1 && slot.sequencing.order <= 12 && text(slot.sequencing.rationale, 220) && text(slot.fatigueConsideration, 220) && (slot.flexibility === null || text(slot.flexibility, 180));
const sessionValid = (session) => allowed(session, ["name", "purpose", "primaryFocus", "secondaryContributions", "plannedWorkingSets", "stimulus", "slots", "durationGuidance", "relationshipToWeek"])
  && text(session.name, 100) && text(session.purpose, 260) && MUSCLES.has(session.primaryFocus) && list(session.secondaryContributions, 5, (item) => MUSCLES.has(item)) && Number.isInteger(session.plannedWorkingSets) && session.plannedWorkingSets >= 1 && session.plannedWorkingSets <= 60 && text(session.stimulus, 220) && list(session.slots, 12, slotValid) && session.slots.length > 0 && text(session.durationGuidance, 220) && text(session.relationshipToWeek, 260) && session.plannedWorkingSets === session.slots.reduce((sum, slot) => sum + slot.sets, 0) && session.slots.some((slot) => slot.primaryMuscle === session.primaryFocus) && sameList([...session.secondaryContributions].sort(), [...new Set(session.slots.flatMap((slot) => slot.secondaryStimulus.map((item) => item.muscleGroup)))].sort()) && session.slots.every((slot, index) => slot.sequencing.order === index + 1);

export function validateRobWeeklyBlueprintRequest(requirements) {
  if (!validRequirements(requirements)) invalid("requirements");
  return requirements;
}

export function blueprintResponseFormat() {
  const secondary = { type: "object", additionalProperties: false, required: ["muscleGroup", "involvement"], properties: { muscleGroup: { type: "string", enum: [...MUSCLES] }, involvement: { type: "string", enum: [...INVOLVEMENT] } } };
  const slot = { type: "object", additionalProperties: false, required: ["primaryMuscle", "secondaryStimulus", "movementPattern", "role", "sets", "repRange", "restSeconds", "priority", "sequencing", "fatigueConsideration", "flexibility"], properties: { primaryMuscle: { type: "string", enum: [...MUSCLES] }, secondaryStimulus: { type: "array", maxItems: 4, items: secondary }, movementPattern: { type: "string", enum: [...PATTERNS] }, role: { type: "string", enum: [...ROLES] }, selectionIntent: { type: ["string", "null"], enum: [...SELECTION_INTENTS, null] }, sets: { type: "integer", minimum: 1, maximum: 12 }, repRange: { type: "string", pattern: "^\\d{1,3}(?:\\s*-\\s*\\d{1,3})?$" }, restSeconds: { type: "integer", minimum: 0, maximum: 600 }, priority: { type: "string", enum: [...PRIORITIES] }, sequencing: { type: "object", additionalProperties: false, required: ["order", "rationale"], properties: { order: { type: "integer", minimum: 1, maximum: 12 }, rationale: { type: "string", minLength: 1, maxLength: 220 } } }, fatigueConsideration: { type: "string", minLength: 1, maxLength: 220 }, flexibility: { type: ["string", "null"], maxLength: 180 } } };
  const session = { type: "object", additionalProperties: false, required: ["name", "purpose", "primaryFocus", "secondaryContributions", "plannedWorkingSets", "stimulus", "slots", "durationGuidance", "relationshipToWeek"], properties: { name: { type: "string", minLength: 1, maxLength: 100 }, purpose: { type: "string", minLength: 1, maxLength: 260 }, primaryFocus: { type: "string", enum: [...MUSCLES] }, secondaryContributions: { type: "array", maxItems: 5, items: { type: "string", enum: [...MUSCLES] } }, plannedWorkingSets: { type: "integer", minimum: 1, maximum: 60 }, stimulus: { type: "string", minLength: 1, maxLength: 220 }, slots: { type: "array", minItems: 1, maxItems: 12, items: slot }, durationGuidance: { type: "string", minLength: 1, maxLength: 220 }, relationshipToWeek: { type: "string", minLength: 1, maxLength: 260 } } };
  return Object.freeze({ type: "json_schema", json_schema: { name: "rob_weekly_blueprint", strict: true, schema: { type: "object", additionalProperties: false, required: ["version", "goal", "daysPerWeek", "weeklyStructure", "priorities", "coverage", "workloadRationale", "movementPatterns", "recoveryConsiderations", "assumptions", "limitations", "sessions"], properties: { version: { type: "integer", const: ROB_WEEKLY_BLUEPRINT_VERSION }, goal: { type: "string" }, daysPerWeek: { type: "integer", minimum: 1, maximum: 6 }, weeklyStructure: { type: "object", additionalProperties: false, required: ["type", "rationale"], properties: { type: { type: "string", minLength: 1, maxLength: 80 }, rationale: { type: "string", minLength: 1, maxLength: 400 } } }, priorities: { type: "array", maxItems: 6, items: { type: "string", enum: [...MUSCLES, "balanced"] } }, coverage: { type: "array", maxItems: 7, items: { type: "object", additionalProperties: false, required: ["muscleGroup", "intent"], properties: { muscleGroup: { type: "string", enum: [...MUSCLES] }, intent: { type: "string", minLength: 1, maxLength: 160 } } } }, workloadRationale: { type: "string", minLength: 1, maxLength: 500 }, movementPatterns: { type: "array", maxItems: 9, items: { type: "string", enum: [...PATTERNS] } }, recoveryConsiderations: { type: "array", maxItems: 8, items: { type: "string", minLength: 1, maxLength: 220 } }, assumptions: { type: "array", maxItems: 8, items: { type: "string", minLength: 1, maxLength: 220 } }, limitations: { type: "array", maxItems: 8, items: { type: "string", minLength: 1, maxLength: 220 } }, sessions: { type: "array", minItems: 1, maxItems: 6, items: session } } } } });
}

export function blueprintMessages(requirements) {
  const policy = createRobWeeklyProgrammingPolicy(requirements);
  const envelope = { goal: policy.goal, priorityEmphasis: policy.priorityEmphasis, coverage: policy.coverage, movementPatternNeeds: policy.movementPatternNeeds, distribution: policy.distribution, sessionWorkload: policy.sessionWorkload, stimulusAccounting: policy.stimulusAccounting, limitations: policy.limitations };
  return [{ role: "system", content: "You are Rob. Return exactly one strict JSON weekly training blueprint, no markdown. Plan the whole week before selecting exercises. Slots describe training roles only: never include exercise names, IDs, catalogue claims, or fictional equipment. Use selectionIntent only when a narrow isolation purpose matters: biceps_flexion, triceps_extension, knee_flexion, knee_extension, lateral_delt, rear_delt, or anterior_delt; otherwise omit it or use null. Use direct hard working sets as the quantitative signal. Secondary-stimulus fields are planning intentions, not verified exercise physiology; Card 5 must resolve every selected exercise against the trusted taxonomy and may revise those claims. Treat unknowns uncertain. A balanced week may use focused sessions; do not require every session to train every muscle. Make training purposeful and challenging within the confirmed duration, without assuming failure training, personal history, recovery capacity, or an exact calendar. Respect constraints. Do not turn advisory policy guidance into hard quotas. A 21-set chest-emphasis session can be appropriate when it has distinct roles and fits a coherent week. Include reasonable assumptions when experience or recovery data is absent." }, { role: "user", content: `CONFIRMED REQUIREMENTS:\n${JSON.stringify(requirements)}\nDETERMINISTIC PLANNING ENVELOPE:\n${JSON.stringify(envelope)}` }];
}

export function parseRobWeeklyBlueprint(raw, requirements) {
  let value; try { value = JSON.parse(typeof raw === "string" ? raw.trim().replace(/^```(?:json)?\s*|\s*```$/gi, "") : ""); } catch { fail("json"); }
  const keys = ["version", "goal", "daysPerWeek", "weeklyStructure", "priorities", "coverage", "workloadRationale", "movementPatterns", "recoveryConsiderations", "assumptions", "limitations", "sessions"];
  const candidateSessions = Array.isArray(value?.sessions) ? value.sessions : [];
  const plannedMuscles = new Set(candidateSessions.flatMap((session) => Array.isArray(session?.slots) ? session.slots.flatMap((slot) => [slot.primaryMuscle, ...(Array.isArray(slot?.secondaryStimulus) ? slot.secondaryStimulus : []).filter((item) => item?.involvement !== "unknown").map((item) => item.muscleGroup)]) : []));
  const plannedPatterns = new Set(candidateSessions.flatMap((session) => Array.isArray(session?.slots) ? session.slots.map((slot) => slot.movementPattern) : []));
  if (!allowed(value, keys) || value.version !== ROB_WEEKLY_BLUEPRINT_VERSION || value.goal !== requirements.goal || value.daysPerWeek !== requirements.daysPerWeek || !allowed(value.weeklyStructure, ["type", "rationale"]) || !text(value.weeklyStructure.type, 80) || !text(value.weeklyStructure.rationale, 400) || !sameList(value.priorities, requirements.priorities) || !list(value.coverage, 7, (item) => allowed(item, ["muscleGroup", "intent"]) && MUSCLES.has(item.muscleGroup) && text(item.intent, 160)) || new Set(value.coverage.map((item) => item.muscleGroup)).size !== value.coverage.length || !value.coverage.every((item) => plannedMuscles.has(item.muscleGroup)) || !text(value.workloadRationale, 500) || !list(value.movementPatterns, 9, (item) => PATTERNS.has(item)) || new Set(value.movementPatterns).size !== value.movementPatterns.length || !sameList([...value.movementPatterns].sort(), [...plannedPatterns].sort()) || !list(value.recoveryConsiderations, 8, (item) => text(item, 220)) || !list(value.assumptions, 8, (item) => text(item, 220)) || !list(value.limitations, 8, (item) => text(item, 220)) || !Array.isArray(value.sessions) || value.sessions.length !== requirements.daysPerWeek || !value.sessions.every(sessionValid)) fail("blueprint_structure");
  return value;
}

export function assessRobWeeklyBlueprint(blueprint, requirements) {
  const policy = createRobWeeklyProgrammingPolicy(requirements); const concerns = []; const direct = new Map(); const secondary = new Map(); const patterns = new Set();
  for (const [routineIndex, session] of blueprint.sessions.entries()) {
    const workload = assessRobSessionWorkload({ sessionMinutes: requirements.sessionMinutes, directWorkingSets: session.plannedWorkingSets, exerciseCount: session.slots.length });
    for (const item of workload.concerns ?? []) concerns.push({ code: `session_${item.code}`, severity: item.code === "below_typical_session_workload" ? "moderate" : "low", routineIndex, explanation: item.reason, advisory: true });
    for (const slot of session.slots) { direct.set(slot.primaryMuscle, (direct.get(slot.primaryMuscle) ?? 0) + slot.sets); patterns.add(slot.movementPattern); for (const item of slot.secondaryStimulus) if (item.involvement !== "unknown") secondary.set(item.muscleGroup, (secondary.get(item.muscleGroup) ?? 0) + 1); }
    const repeatedRoles = new Map();
    for (const [slotIndex, slot] of session.slots.entries()) { const key = `${slot.primaryMuscle}:${slot.movementPattern}:${slot.role}`; repeatedRoles.set(key, [...(repeatedRoles.get(key) ?? []), slotIndex]); }
    for (const [key, slotIndices] of repeatedRoles) if (slotIndices.length >= 3) concerns.push({ code: "redundant_slot_roles", severity: "moderate", routineIndex, slotIndices, explanation: `Three or more ${key.replaceAll(":", " ")} slots appear in one session; confirm that each has a distinct programming purpose.`, advisory: true });
    for (let index = 0; index < session.slots.length - 1; index += 1) { const first = session.slots[index]; const second = session.slots[index + 1]; if (["horizontal_push", "vertical_push"].includes(first.movementPattern) && ["horizontal_push", "vertical_push"].includes(second.movementPattern)) concerns.push({ code: "adjacent_pressing_fatigue", severity: "low", routineIndex, slotIndices: [index, index + 1], explanation: "Adjacent pressing roles accumulate local fatigue; confirm their order supports the session priority.", advisory: true }); }
  }
  for (const item of policy.coverage.filter((coverage) => coverage.expectation === "baseline_required")) if (!direct.get(item.muscleGroup) && !secondary.get(item.muscleGroup)) concerns.push({ code: "baseline_coverage_gap", severity: "high", muscleGroup: item.muscleGroup, explanation: `No planned primary or qualitative secondary stimulus supports ${item.muscleGroup} across the week.`, advisory: true });
  for (const item of policy.movementPatternNeeds.filter((need) => need.expectation === "seek_when_compatible")) if (!patterns.has(item.pattern)) concerns.push({ code: "movement_pattern_gap", severity: "moderate", movementPattern: item.pattern, explanation: `The balanced blueprint has no ${item.pattern.replaceAll("_", " ")} slot.`, advisory: true });
  return { advisoryOnly: true, directWorkingSetsByPrimaryMuscle: Object.fromEntries([...direct.entries()].sort()), qualitativeSecondaryCounts: Object.fromEntries([...secondary.entries()].sort()), concerns, limitations: policy.limitations };
}

export async function generateRobWeeklyBlueprint(requirements, { provider, maxOutputTokens = ROB_WEEKLY_BLUEPRINT_MAX_OUTPUT_TOKENS }) {
  validateRobWeeklyBlueprintRequest(requirements);
  const result = await provider.generate({ messages: blueprintMessages(requirements), maxOutputTokens, responseFormat: blueprintResponseFormat(), requireResponseFormat: true });
  try { const blueprint = parseRobWeeklyBlueprint(result.text, requirements); return { model: result.model, usage: result.usage, finishReason: result.finishReason ?? null, blueprint, quality: assessRobWeeklyBlueprint(blueprint, requirements) }; }
  catch (error) { error.blueprintDiagnostic = { finishReason: result.finishReason ?? null, responseCharacterLength: typeof result.text === "string" ? result.text.length : null }; throw error; }
}

// Character-based estimate for test-budget measurement only; it is intentionally
// conservative and does not claim tokenizer-exact accounting across providers.
export function estimateRobWeeklyBlueprintOutputTokens(blueprint) { return Math.ceil(JSON.stringify(blueprint).length / 4); }
